# -*- coding: utf-8 -*-
"""physics simulator - group interactions

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kzn9eM9P4hg34NyycFbvOI_CMzGzUYsV



- train hgraph witgh random structure (should be very poor)
- train hgraph with gt structure (should be perfect)

# Create simulations
"""

import numpy as np
import numpy_indexed as npi
import pdb
import os

import torch
from torch_geometric.data import DataLoader
import torch.nn as nn
import torch.nn.functional as F
from torch_geometric.data import Data


from models import *
from dataset import *
from utils import *
from utils_eval_ksample import *
from hypergraph_predictor import HypergraphPredictor, HypergraphPredictorSeq

DEVICE = 'cuda:0'
import wandb
import argparse
import transformers

torch.set_num_threads(1)

def str2bool(v):
    if v.lower() in ('yes', 'true', 't', 'y', '1'):
        return True
    elif v.lower() in ('no', 'false', 'f', 'n', '0'):
        return False
    else:
        raise argparse.ArgumentTypeError('Boolean value expected.')

parser = argparse.ArgumentParser()
parser.add_argument('--tag', default='hyperparameter_tuning')
parser.add_argument('--num_layers', type=int, default=1)
parser.add_argument('--heads', type=int, default=1)
parser.add_argument('--num_classes', type=int, default=2)
parser.add_argument('--num_features', type=int, default=5)
parser.add_argument('--MLP_hidden', type=int, default=256)
parser.add_argument('--MLP_num_layers', type=int, default=3)
parser.add_argument('--lr', type=float, default=0.0001)
parser.add_argument('--dropout', type=float, default=0.0)
parser.add_argument('--MLP_norm',  default='None')
parser.add_argument('--batch_size', type=int, default=64)
parser.add_argument('--num_epochs', type=int, default=500)
parser.add_argument('--connectivity', default='gt')
parser.add_argument('--num_nodes', type=int, default=1)

#slot-attention specific
parser.add_argument('--num_iter', default=3, type=int)
parser.add_argument('--temperature', default=1.0, type=float)
parser.add_argument('--slot_nonlin', default='sigmoid', type=str, choices=['sigmoid', 'softmax', 'sparsemax', 'None'])
parser.add_argument('--init_slot', default='rand', type=str, choices=['rand', 'hgraph', 'rand_embedding'])
parser.add_argument('--selection_type', default='simple', type=str, choices=['gumbel_softmax', 'imle', 'aimle', 'simple'])
parser.add_argument('--slot_k', default=3, type=int)
parser.add_argument('--num_slots', default=2, type=int)
parser.add_argument('--check_learned_params', type=str2bool, default=False)
parser.add_argument('--logits_activation', type=str, default='logsoftmax', choices=['logsoftmax', 'logsigmoid', 'None'])


parser.add_argument('--model_type', type=str, default='HGNN', choices=['HGNN', 'AllDeepSets', 'AllDeepSetsOrig'])
parser.add_argument('--encoder_type', type=str, default='tempCNN', choices=['tempCNN', 'MLP'])

parser.add_argument('--noise_distribution', type=str, default='gumbel', choices=['gumbel', 'sog']) #this is just for aimle
parser.add_argument('--imle_beta', default=10.0, type=float)

parser.add_argument('--trick_fixed_point', type=str, default='none') #'none', 'neumann' or 'bi-level'
parser.add_argument('--add_self_loop', type=str2bool, default=True)

parser.add_argument('--enc_len', default=5, type=int)
parser.add_argument('--ld', default=10, type=float) #learningrate decay factor for predictor
parser.add_argument('--degree_detached', type=str2bool, default=True)

parser.add_argument('--dataset', type=str, default='nba')
parser.add_argument('--deterministic', type=str2bool, default=True)
parser.add_argument('--long_history', type=str2bool, default=False)
parser.add_argument('--add_velocity', type=str2bool, default=True)

parser.add_argument('--sequential', type=str2bool, default=True)
config_defaults = parser.parse_args()

"""# Train the models for trajectory prediction"""

add_velocity = config_defaults.add_velocity

def visualize(model, model_pred, val_loader, epoch, table):
    """ Code used to visualise the predicted higher-order structure
    this can be used both as an interpretation tool
    and to debug the model.
    """

    first_batch = next(iter(val_loader))
    num_display = min(3, len(first_batch))

    num_nodes = 11
    model.eval()
    model_pred.eval()
    for graph_idx in range(num_display):
        crt_data = first_batch[graph_idx]

        timesteps =  config_defaults.enc_len
        y_hat_tf, y, pred_edge_index_tf, _, _ = forward_step_teacher_forcing(crt_data, model, model_pred, timesteps)
        y_hat_roll, y, pred_edge_index_roll, _, _ = forward_step_pred(crt_data, model, model_pred, timesteps)

        y = y.cpu().numpy().reshape((num_nodes, -1, 2))
        y = np.transpose(y,(1,0,2))

        y_hat_tf = y_hat_tf.detach().cpu().numpy().reshape((num_nodes, -1, 2))
        y_hat_tf = np.transpose(y_hat_tf,(1,0,2))

        y_hat_roll = y_hat_roll.detach().cpu().numpy().reshape((num_nodes, -1, 2))
        y_hat_roll = np.transpose(y_hat_roll,(1,0,2))

        # printing the groud truth
        f_gt = draw(y[:,:,:], None, './gt.jpg', num_nodes=11)
        gt_image = wandb.Image(f_gt)

        pred_edge_index_tf = pred_edge_index_tf.detach().cpu().numpy()
        pred_edge_index_tf = npi.group_by(pred_edge_index_tf[1, :]).split(pred_edge_index_tf[0, :])

        # printing the teacher-forcing trajectory
        f_tf = draw(y_hat_tf[:,:,:], pred_edge_index_tf, './pred_tf.jpg', num_nodes=11)
        teacher_forcing_image = wandb.Image(f_tf)

        # printing the multi-step rolled trajectory
        pred_edge_index_roll = pred_edge_index_roll.detach().cpu().numpy()
        pred_edge_index_roll = npi.group_by(pred_edge_index_roll[1, :]).split(pred_edge_index_roll[0, :])
        f_roll = draw(y_hat_roll[:,:,:], pred_edge_index_roll, './pred_roll.jpg', num_nodes=11)
        roll_pred_image = wandb.Image(f_roll) 

        id = f'{epoch}_{graph_idx}'
        table.add_row(id, teacher_forcing_image, roll_pred_image, gt_image, epoch)
    return table

def forward_step_teacher_forcing(data, model, model_predictor,timesteps):
    """ One feed-forward step with teacher-forcing (used during TRAINING).

    During training, we use a teacher-forcing approach: at each time step t, we
    feed as input the real position from the previous timestep t-1.

    Output: (pred, target, edge_index, H, slots) tuple.
    """
    # Run the forward pass for HGNN.
    batch = data.clone().to(DEVICE)

    #add velocity as features to the encoder and decoder
    if add_velocity:
        x_vel = batch.x[:,1:,:2] - batch.x[:,:-1, :2]
        x_vel = torch.cat([x_vel[:,[0]], x_vel], dim=1)
        x = torch.cat((batch.x,x_vel),dim=-1)
    else:
        x = batch.x

    x_enc = x[:,:timesteps,:]
    x_dec = x[:,:,:]
    y_dec = batch.y[:,:,:]


    x_enc = torch.permute(x_enc, (1,0,2))
    num_nodes = x.shape[0]


    edge_index, _, slots = model_predictor(x_enc) #H: bs x num_slots x num_nodes
    
    H = torch.block_diag(*torch.unbind(slots, dim=0))
    H = torch.permute(H, (1,0))

    # add self loops if 
    if config_defaults.add_self_loop:
        H = add_extra_self_loops_dense(H,  num_nodes) 
    
    #batch.x: num_nodes_batch x num_timesteps x 2; H: num_nodes_batch x num_edges_batch
    y_hat  = model(x_dec, H)

    # (n_timesteps x n_nodes) x output_dim -> (n_nodes x n_timesteps) x output_dim
    y = y_dec.reshape(-1,2)
    y_hat = y_hat.reshape(-1,2)

    return y_hat, y, edge_index, H, slots

def forward_step_pred(batch, model, model_predictor, timesteps):
    """ One feed-forward step using previous predictions as input (EVAL only),

    Run for the first `timesteps` positions in the input.
    Output: (pred, target, edge_index, H, slots) tuple.
    """

    # ->  n_nodes x dim x n_timesteps
    batch = batch.to(DEVICE)
    timesteps_enc = config_defaults.enc_len
    timesteps_dec = timesteps
    assert timesteps_enc+timesteps_dec <= batch.x.shape[1]+1


    batch_enc_x = batch.x[:,:timesteps_enc,:]
    batch_dec_x = batch.x[:,timesteps_enc-1:timesteps_enc-1+timesteps_dec,:]
    batch_dec_y = batch.y[:,timesteps_enc-1:timesteps_enc-1+timesteps_dec,:]
 
    #add velocity as features to the encoder
    if add_velocity:
        x_vel = batch_enc_x[:,1:,:2] - batch_enc_x[:,:-1, :2]
        x_vel = torch.cat([x_vel[:,[0]], x_vel], dim=1)
        batch_enc_x = torch.cat((batch_enc_x, x_vel),dim=-1)

    x_enc = torch.permute(batch_enc_x, (1,0,2))
    num_nodes = batch.x.shape[0]

    edge_index, _, slots = model_predictor(x_enc)
    H = torch.block_diag(*torch.unbind(slots, dim=0))
    H = torch.permute(H, (1,0))
    
    # add self loops if needed
    if config_defaults.add_self_loop:
        H = add_extra_self_loops_dense(H,  num_nodes) 

    all_feats = batch_dec_x[:,0,:].unsqueeze(1) #n_nodes x 1 x 2 # this is because forward consider timesteps as well
    feats = all_feats[:,:,:2] # just position
    category = all_feats[:,:,2:5] # just category
    prev_feats =  batch_enc_x[:,-2,:2].unsqueeze(1)

    # Run forward for each timestep, using the previous prediction as input.
    all_y_hat = []
    all_y = []
    
    for i in range(timesteps_dec):
      #add velocity as features to the dencoder, based on the previous prediction
      if add_velocity:
        crt_x_vel = (feats - prev_feats).detach()
        prev_feats = feats.clone()
        feats = torch.cat([feats, category, crt_x_vel], dim=-1)
      else:
        feats = torch.cat([feats, category], dim=-1)

      feats = model(feats, H)
      all_y_hat.append(feats.clone().squeeze(1))
      all_y.append(batch_dec_y[:,i,:])

    #n_timesteps x n_nodes x output_dim
    all_y_hat = torch.stack(all_y_hat, 0)
    #n_nodes x n_timesteps x output_dim -> (n_nodes * n_timesteps) x output_dim
    all_y_hat = all_y_hat.permute((1,0,2)).reshape(-1,all_y_hat.shape[-1])

    all_y = torch.stack(all_y, 0)
    all_y = all_y.permute((1,0,2)).reshape(-1,all_y.shape[-1])

    # all_y_hat: n_nodes x n_timesteps x output_dim
    return all_y_hat, all_y, edge_index, H, slots


import torch.optim as optim

def train_epoch(data_loader, model, model_predictor, optimiser, optimiser_pred, epoch, loss_fct, scheduler, scheduler_pred, loss_tmp):
    """ Train the model for one epoch. """
    model.train()
    model_predictor.train()

    param_checker =  LearnedParamChecker(model)
    param_checker_pred =  LearnedParamChecker(model_predictor)

    for _, batch in enumerate(data_loader):
        optimiser.zero_grad()
        optimiser_pred.zero_grad()
        # For training, we always use teacher forcing.
        y_hat, y, _, _, _ = forward_step_teacher_forcing(batch, model, model_predictor, config_defaults.enc_len) #

        loss = loss_fct(y_hat, y)
        loss.backward()

        optimiser.step()
        optimiser_pred.step()
    
    scheduler.step()
    scheduler_pred.step()


    if epoch %10 == 0:
        param_checker.compare_current_initial_params()
        param_checker_pred.compare_current_initial_params()


    return loss.item()

def eval_epoch(data_loader, model, model_predictor, loss_fct, loss_tmp, forward_fct, num_rollout=-1, extra_metrics=False):
    """ Evaluate the model. """
    model.eval()
    model_predictor.eval()
    num_iter = 0
    loss_eval = 0

    if extra_metrics:
        assert num_rollout >= 10

    with torch.no_grad():
        num_examples = 0
        other_metrics = np.array([0.0] * 8)
        for i, batch in enumerate(data_loader):
            # For evaluation, we switch between teacher forcing for validation and
            # using previous predictions at test-time.
            if num_rollout == -1:
                num_rollout = config_defaults.enc_len
            y_hat, y, _, _, _ = forward_fct(batch, model, model_predictor, num_rollout)
            
            if extra_metrics:
                #n_nodes x n_timesteps x output_dim -> (n_nodes * n_timesteps) x output_dim
                y_hat = y_hat.reshape(-1, num_rollout, y_hat.shape[-1]).unsqueeze(0)
                y = y.reshape(-1, num_rollout, y.shape[-1]).unsqueeze(0)
                num_examples += y.shape[1] 
                other_metrics += predict_metrics(y_hat, y)

            loss = loss_fct(y_hat, y)
            loss_eval += loss.item()
            num_iter = num_iter + 1
    if extra_metrics:
        other_metrics = [x/ num_examples for x in other_metrics]
    loss_eval /= num_iter
    return loss_eval, other_metrics



def train_eval_loop(model, model_predictor, train_loader, val_loader, test_loader,
               loss_fct, loss_tmp, num_epochs=100, lr=0.0005):
    """ Train/evaluate the model for `num_epochs` epochs. """
    # Instantiate our optimiser.
    optimiser = optim.Adam(list(model.parameters()), lr=lr)
    optimiser_pred = optim.Adam(list(model_predictor.parameters()), lr=lr/config_defaults.ld)

    # scheduler = torch.optim.lr_scheduler.MultiStepLR(optimiser, milestones=[config_defaults.optimise_processor_only], gamma=10)
    scheduler = transformers.get_constant_schedule_with_warmup(optimiser, 
                                                         num_warmup_steps=0)
    scheduler_pred = transformers.get_constant_schedule_with_warmup(optimiser_pred, 
                                                         num_warmup_steps=0)

    # Initial evaluation (before training).
    val_loss, _ = eval_epoch(
        val_loader, model, model_predictor, loss_fct, loss_tmp, forward_step_teacher_forcing)
    train_loss, _ = eval_epoch(
        train_loader, model, model_predictor, loss_fct, loss_tmp, forward_step_teacher_forcing)


    # training_stats = update_stats(training_stats, epoch_stats)
    print(f"[Epoch 0]",
          f"train loss: {train_loss:.5f} val loss: {val_loss:.5f}")

    train_loss_1step = []
    valid_loss_1step = []

    table = wandb.Table(columns=["ID", "teacher_forcing", "roll_pred", "gt", "epoch"])
    best_valid_loss_1step = 1000.0
    test_loss = 1000.0

    for epoch in range(num_epochs):
      train_loss  = train_epoch(
          train_loader, model, model_predictor, optimiser, optimiser_pred,  epoch, loss_fct, scheduler, scheduler_pred, loss_tmp)
   
      val_loss, _ = eval_epoch(
          val_loader, model, model_predictor, loss_fct, loss_tmp, forward_step_teacher_forcing)

      torch.set_printoptions(precision=10)
      # Store the loss and the computed metric for the final plot.
      train_loss_1step.append(train_loss)
      valid_loss_1step.append(val_loss)

      if val_loss <= best_valid_loss_1step:
        best_valid_loss_1step = val_loss
        test_loss, _ = eval_epoch(
                        test_loader, model, model_predictor, loss_fct, loss_tmp, forward_step_teacher_forcing)
        test_loss_25steps, test_loss_other_metrics = eval_epoch(
            test_loader, model, model_predictor, loss_fct, loss_tmp, forward_step_pred, num_rollout=10, extra_metrics=True)
        test_loss_5steps, _ = eval_epoch(
            test_loader, model, model_predictor, loss_fct, loss_tmp, forward_step_pred, num_rollout=5)
        wandb.log({
                f'test_loss_1step': test_loss,
                f'test_loss_25steps': test_loss_25steps,
                f'test_loss_5steps': test_loss_5steps
        }, step=epoch)

        #Save the currently best model
        model_saved = {'model_dict': model.state_dict(), 'model_predictor_dict': model_predictor.state_dict(), 
                        'optimiser': optimiser.state_dict(),  'optimiser_pred':optimiser_pred.state_dict(),
                        'epoch': epoch + 1,'model_cfg': config_defaults}
        parent_dir = f'./models/{wandb.run.id}'
        if not os.path.exists(parent_dir):
            os.mkdir(parent_dir)
        saved_path = os.path.join(parent_dir,'best_model.p')
        torch.save(model_saved, saved_path)
        print(f'Model saved in {saved_path}')
        log_corpus_extra = {
                f'test_ADE_1sec': test_loss_other_metrics[0],
                f'test_ADE_2sec': test_loss_other_metrics[1],
                f'test_ADE_3sec': test_loss_other_metrics[2],
                f'test_ADE_4sec': test_loss_other_metrics[3],
                f'test_FDE_1sec': test_loss_other_metrics[4],
                f'test_FDE_2sec': test_loss_other_metrics[5],
                f'test_FDE_3sec': test_loss_other_metrics[6],
                f'test_FDE_4sec': test_loss_other_metrics[7],
            }
      
        wandb.log(log_corpus_extra, step=epoch)
        print(log_corpus_extra)
      log_corpus = {
                f'train_loss_1step': train_loss_1step[epoch],
                f'valid_loss_1step': valid_loss_1step[epoch],
                f'best_valid_loss_1step': best_valid_loss_1step,
                f'lr': optimiser.param_groups[0]["lr"]
            }
      wandb.log(log_corpus, step=epoch)
      

      if epoch % 10 == 0:
        train_loss_10steps, _ = eval_epoch(
            train_loader, model,  model_predictor, loss_fct, loss_tmp, forward_step_pred, num_rollout=10)
        valid_loss_10steps, valid_loss_other_metrics = eval_epoch(
            val_loader, model, model_predictor, loss_fct, loss_tmp, forward_step_pred, num_rollout=10, extra_metrics=True)
        
        train_loss_5steps, _ = eval_epoch(
            train_loader, model,  model_predictor, loss_fct, loss_tmp, forward_step_pred, num_rollout=5)
        valid_loss_5steps, _ = eval_epoch(
            val_loader, model, model_predictor, loss_fct, loss_tmp, forward_step_pred, num_rollout=5)
       
        log_corpus = {
                f'train_loss_10steps': train_loss_10steps,
                f'valid_loss_10steps': valid_loss_10steps,
                f'train_loss_5steps': train_loss_5steps,
                f'valid_loss_5steps': valid_loss_5steps
            }
        log_corpus_extra = {
                f'valid_ADE_1sec': valid_loss_other_metrics[0],
                f'valid_ADE_2sec': valid_loss_other_metrics[1],
                f'valid_ADE_3sec': valid_loss_other_metrics[2],
                f'valid_ADE_4sec': valid_loss_other_metrics[3],
                f'valid_FDE_1sec': valid_loss_other_metrics[4],
                f'valid_FDE_2sec': valid_loss_other_metrics[5],
                f'valid_FDE_3sec': valid_loss_other_metrics[6],
                f'valid_FDE_4sec': valid_loss_other_metrics[7],
            }
        
        wandb.log(log_corpus, step=epoch)
        wandb.log(log_corpus_extra, step=epoch)

        crt_lr = optimiser.param_groups[0]["lr"]
        print(f"[Epoch {epoch+1}]",
              f"lr {crt_lr}\n",
              f"train loss 1step: {train_loss:.5f} val loss 1step: {val_loss:.5f}\n",
              f"train loss 5step: {train_loss_5steps:.5f} val loss 5step: {valid_loss_5steps:.5f}\n",
              f"train loss 10step: {train_loss_10steps:.5f} val loss 10step: {valid_loss_10steps:.5f}\n")
        print(log_corpus_extra)

      if epoch % 50 == 0:
          table = visualize(model, model_predictor, val_loader, epoch, table)
    
    # Eval using k sample
    if config_defaults.model_type == 'AllDeepSets':    
        model_ksample =  DenseAllDeepSetsNBA(config_defaults)
    elif config_defaults.model_type == 'AllDeepSetsOrig':    
        model_ksample =  DenseAllDeepSetsNBAOrig(config_defaults)

    model_predictor_ksample = HypergraphPredictorSeq(
                        config_defaults.num_slots, config_defaults.MLP_hidden, config_defaults.num_iter, 
                        eps = 1e-8, hidden_dim =config_defaults.MLP_hidden, 
                        temperature=config_defaults.temperature, nonlin=config_defaults.slot_nonlin, init_slot=config_defaults.init_slot, 
                        slot_k=config_defaults.slot_k, trick_fixed_point=config_defaults.trick_fixed_point, selector=config_defaults.selection_type,
                        logits_activation = config_defaults.logits_activation, 
                        encoder_type=config_defaults.encoder_type, noise_distribution=config_defaults.noise_distribution,
                        beta=config_defaults.imle_beta, enc_len=config_defaults.enc_len, deterministic=config_defaults.deterministic,
                        num_nodes=model_predictor.num_nodes, in_feat=model_predictor.in_feat,
                        long_history=config_defaults.long_history, nb_sample=20
                        )
    
    
    checkpoint = torch.load(saved_path)

    model_ksample = model_ksample.to(DEVICE)
    model_predictor_ksample = model_predictor_ksample.to(DEVICE)

    model_ksample.load_state_dict(checkpoint['model_dict'], strict=True)
    model_predictor_ksample.load_state_dict(checkpoint['model_predictor_dict'], strict=True)

    log_corpus_extra_ksample = eval_k_sample(val_loader, model_ksample, model_predictor_ksample, 
                        num_rollout=10, extra_metrics=True, nb_sample=20, add_velocity=add_velocity,
                        enc_len=config_defaults.enc_len, add_self_loop=config_defaults.add_self_loop)
    print(log_corpus_extra_ksample)
    wandb.log(log_corpus_extra_ksample)

    wandb.log({"Table": table})
    return 0

 
def main(num_examples):
    
    os.environ["WANDB_AGENT_MAX_INITIAL_FAILURES"]= "200"
    wandb.init(sync_tensorboard=False, project='slot_synth', reinit = False, config = config_defaults, entity='hyper_graphs', tags=[config_defaults.tag])
    print('Monitoring using wandb')

    config_defaults.num_nodes = 13
   
    print("Configuration:")
    print(config_defaults)

    small_train_dataset = NBADataset('../../NBA-Player-Movements/train.npy', 'train', num_examples)
    small_valid_dataset = NBADataset('../../NBA-Player-Movements/test.npy', 'valid', num_examples)
    small_test_dataset = NBADataset('../../NBA-Player-Movements/test.npy', 'test', num_examples)

    train_loader = DataLoader(small_train_dataset, batch_size=config_defaults.batch_size, shuffle=True)
    valid_loader = DataLoader(small_valid_dataset, batch_size=config_defaults.batch_size, shuffle=False)
    test_loader = DataLoader(small_test_dataset, batch_size=config_defaults.batch_size, shuffle=False)

    config_defaults.timesteps = small_train_dataset.n_timesteps

    # Create the model
    # model = SlotUniGCNII(config_defaults)
    if config_defaults.model_type == 'HGNN':
        model =  HCHA(config_defaults)
    elif config_defaults.model_type == 'AllDeepSets':    
        model =  DenseAllDeepSetsNBA(config_defaults)
    elif config_defaults.model_type == 'AllDeepSetsOrig':    
        model =  DenseAllDeepSetsNBAOrig(config_defaults)

    if add_velocity:
        in_feat = 4+3
    else:
        in_feat = 2+3

    if config_defaults.sequential:
        model_predictor = HypergraphPredictorSeq(
                        config_defaults.num_slots, config_defaults.MLP_hidden, config_defaults.num_iter, 
                        eps = 1e-8, hidden_dim =config_defaults.MLP_hidden, 
                        temperature=config_defaults.temperature,  nonlin=config_defaults.slot_nonlin,  init_slot=config_defaults.init_slot, 
                        slot_k=config_defaults.slot_k, trick_fixed_point=config_defaults.trick_fixed_point, selector=config_defaults.selection_type,
                        logits_activation = config_defaults.logits_activation, 
                        encoder_type=config_defaults.encoder_type, noise_distribution=config_defaults.noise_distribution,
                        beta=config_defaults.imle_beta, enc_len=config_defaults.enc_len, deterministic=config_defaults.deterministic,
                        num_nodes=small_train_dataset.n_nodes, in_feat=in_feat, long_history=config_defaults.long_history)
    else:
        model_predictor = HypergraphPredictor(
                        config_defaults.num_slots, config_defaults.MLP_hidden, config_defaults.num_iter, 
                        eps = 1e-8, hidden_dim =config_defaults.MLP_hidden,
                        temperature=config_defaults.temperature, nonlin=config_defaults.slot_nonlin, init_slot=config_defaults.init_slot, 
                        slot_k=config_defaults.slot_k,  trick_fixed_point=config_defaults.trick_fixed_point, selector=config_defaults.selection_type,  
                        logits_activation = config_defaults.logits_activation, 
                        encoder_type=config_defaults.encoder_type, noise_distribution=config_defaults.noise_distribution,
                        beta=config_defaults.imle_beta, in_feat=in_feat, enc_len=config_defaults.enc_len,
                        num_nodes=small_train_dataset.n_nodes,)

    model = model.to(DEVICE)
    model_predictor = model_predictor.to(DEVICE)

    wandb.watch(model)

    # Train the model.
    _ = train_eval_loop(model, model_predictor, train_loader, valid_loader,
                                        test_loader, loss_fct=F.mse_loss, loss_tmp= F.binary_cross_entropy, num_epochs=config_defaults.num_epochs,lr=config_defaults.lr)

    return model, model_predictor, small_train_dataset, small_valid_dataset


num_examples = 0
model, model_pred, small_train_dataset, small_valid_dataset = main(num_examples)



